#!/usr/bin/env ruby

require_relative "./controllers/GameController.rb"
require_relative "./models/game-setup.rb"
require "tty-prompt"
require "tty-file"
require "tty-table"
require "colorize"

####################################################################################
##########################         START THE GAME         ##########################
####################################################################################

# Show title screen
showtitlescreen(displayboard())

# Initialise prompt
prompt = TTY::Prompt.new(symbols: {marker: " "})

# Ask for user prompt
begin
	puts "\n"
	halign = 95
	choices = 
	{
		"New Game".center(halign) => 1,
		"Simulation Mode".center(halign) => 2,
		"Instructions".center(halign) => 3,
		"Load Previous Games".center(halign) => 4,
		"Quit Game".center(halign) => 5
	}
	
	request = prompt.select("Choose from below: (Use ↑↓ arrow keys to select)\n".center(100), choices, show_help: :never, cycle: true)

	GameController::create 			if request == 1
	GameController::simulation 		if request == 2
	GameController::instructions	if request == 3
	GameController::load_games		if request == 4
	request = prompt.select("Are you sure you want to quit?\n".center(100), {"Yes".center(100)=>0, "No".center(100)=>5}, show_help: :never, cycle: true) if request == 5
end until request == 0

# End of game
puts "\n\n"
puts "Goodbye!".center(100)
puts "\n\n"