#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './controllers/game_controller'
require_relative './gamestats'
require_relative './views/prompts'
require_relative './views/display'
require 'tty-prompt'
require 'colorize'
require 'tty-box'

####################################################################################
##########################         START THE GAME         ##########################
####################################################################################

# Check command-line arguments
Views::GameInfo.showhelp	if ['--h', '-h', '--help', '-help'].include? ARGV[0]
Views::GameInfo.showversion	if ['--v', '-v', '--ver', '-ver', '--version', '-version'].include? ARGV[0]
Views::GameInfo.showabout	if ['--a', '-a', '--about', '-about'].include? ARGV[0]
(ARGV[1].nil? ? gamestats : gamestats(ARGV[1]))	if ['--gs', '-stats', '--gamestats', '-gs', '--stats',
                                                    '-gamestats'].include? ARGV[0]

unless ARGV[0]
  Views::Display.titlescreen
  halign = 95

  # Ask for user prompt
  loop do
    puts "\n"

    choices =
      {
        'New Game'.center(halign)	=> 1,
        'Simulation Mode'.center(halign)	=> 2,
        'Instructions'.center(halign)	=> 3,
        'Load Previous Games'.center(halign)	=> 4,
        'Quit Game'.center(halign)	=> 5
      }

    request = Views::Prompts.prompt('Choose from below: (Use ↑↓ arrow keys to select)', choices)
    GameController.create          if request == 1
    GameController.simulation      if request == 2
    GameController.instructions    if request == 3
    GameController.load_games      if request == 4
    if request == 5
      request = Views::Prompts.prompt('Are you sure you want to quit?',
                                      { 'Yes'.center(halign) => 0, 'No'.center(halign) => 5 })
    end
    break if request.zero?
  end

  # End of game
  puts "\n\n"
  puts 'Goodbye!'.center(halign)
  puts "\n\n"
end
