#!/usr/bin/env ruby

require_relative "./controllers/GameController.rb"
require_relative "./models/game-setup.rb"
require 'tty-prompt'

####################################################################################
##########################         START THE GAME         ##########################
####################################################################################

# Show title screen
showtitlescreen(displayboard())

# Initialise prompt
prompt = TTY::Prompt.new(symbols: {marker: " "})

# Ask for user prompt
begin
	puts "\n\n"
	choices = {"New Game\n".center(100) => 1, "Simulation Mode\n".center(100) => 2, "Instructions\n".center(100) => 3, "Load Previous Games\n" => 4, "Quit Game\n".center(100) => 0}
	request = prompt.select("Choose from below: (Use ↑↓ arrow keys to select)\n".center(100), choices, show_help: :never)

	GameController::create 			if request == 1
	GameController::simulation 		if request == 2
	GameController::instructions	if request == 3
	GameController::load_games		if request == 4
	
end until request == 0

# End of game
puts "\n\n"
puts "Goodbye!".center(100)
puts "\n\n"